### ISSUE TITLE
When should we set the next skype meeting ?

### ISSUE THREAD

**Issue by callicles** [gitlinks/github-rank-project#11]
2 weeks from now ?

Objectives for next meeting:
- [x] have a badge
- [x] be able to get all the metrics we need from github
- [ ] be able to connect on our web app with github

**Comment by pocman** [comment]
The _all_ metrics seems a bit hard to reached.

**Comment by callicles** [comment]
ok, but let's set a date:  Monday 8th June

**Comment by pocman** [comment]
Ok for me.
Le 1 juin 2015 7:50 PM, "Nicolas Joseph" notifications@github.com a
écrit :

**Comment by callicles** [comment]
@jacobtardieu When are you available ?

**Comment by osakatand** [comment]
Sorry for the late reply, not on monday :/ But for now any other day is fine by me.

**Comment by callicles** [comment]
Tuesday ? @pocman

**Comment by pocman** [comment]
Ok.

**Comment by pocman** [comment]
In fact, it's not that great for me. :-\
I will be available on Tuesday but only between 6 and 7pm.

**Comment by callicles** [comment]
Lets find another date then. Wednesday is a no go for me. How about thursday ?

**Comment by pocman** [comment]
No go for me on Thursday :-\
Maybe after lunch around 1pm?
Le 7 juin 2015 9:59 PM, "Nicolas Joseph" notifications@github.com a
écrit :

**Comment by callicles** [comment]
Every Monday on 20h30
