### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by callicles** [gitlinks/github-rank-project#19]
We could use shield.io for badge generation:

![Gitrank](https://img.shields.io/badge/gitrank-5-brightgreen.svg)
![Gitrank](https://img.shields.io/badge/gitrank-4-green.svg)
![Gitrank](https://img.shields.io/badge/gitrank-3-yellow.svg)
![Gitrank](https://img.shields.io/badge/gitrank-2-orange.svg)
![Gitrank](https://img.shields.io/badge/gitrank-1-red.svg)

**Comment by osakatand** [comment]
Not bad, especially if it's easy to do. But maybe we should make the scale more explicit (e.g. by using 1/5, 5/5, or stars).

**Comment by callicles** [comment]
I agree, and gitrank is not that explicit.

![badge](https://img.shields.io/badge/gitrank%20score-3%2F5-yellow.svg)
