### ISSUE TITLE
Compare DBs to store text

### ISSUE THREAD

**Issue by osakatand** [gitlinks/github-rank-project#26]
To store user comments and feedback, compare the performances of several DBs.
Neo4j would be the easier but it needs to be validated. There is also MySQL and PostgreSQL.

**Comment by callicles** [comment]
http://grokbase.com/t/gg/neo4j/135w1kw5xr/storing-document-text-in-node-property-text-analysis-possible

Looked into that for the graph model and looks like we should not face issues for feedbacks.

**Comment by callicles** [comment]
@sheymann have you heard about difficulties in storing a lot of text in neo ?

**Comment by sheymann** [comment]
Yes for long texts, because text blobs are truncated but I don't know the limit. Neo4j is not a document store. It's alright if you have texts such as paragraphs.

**Comment by osakatand** [comment]
After some quick researches: 
- MySQL can store text up to 4Gb (for the LONGTEXT type). The TEXT, MEDIUMTEXT and LONGTEXT types store actual data in a file and only the reference to that file is put into the table.
- PostgreSQL can also store large texts up to 1Gb of data.
- Neo4J seems to be able to handle reasonabely sized text in nodes and since it uses Lucene for indexing having text is not a real issue. 

In our case the text content is rather short (we could even have a limit in comments and feedbacks) so I think we could for now use Neo4j. We'll make some experiments with the first prototype.

**Comment by osakatand** [comment]
We'll use Neo4j!
