### ISSUE TITLE
How to prevent rivals from down rating each others libraries on no legitimate reason.

### ISSUE THREAD

**Issue by callicles** [gitlinks/github-rank-project#6]
First there is the social predicament that there is no interest in not giving a honest opinion. Bad ratings of rival repositories will be spotted very fast. As a consequence this behaviour will result in the bad credibility for the user.

Do we need to think of some more technical solution to prevent this kind of thing or should it regulate it self ?

**Comment by pocman** [comment]
It clearly has no place in a MVP.

**Comment by callicles** [comment]
ok, I guess we can close it then.
