### ISSUE TITLE
What database to use ?

### ISSUE THREAD

**Issue by callicles** [gitlinks/github-rank-project#7]
I think we could most gain by building everything on the top of a graph Database. A lot of insight could be then extracted from the votes and relations between people and repositories.

As I do know the database, it would be easier to go with neo4j. Other alternatives/proposals ?

**Comment by pocman** [comment]
It's clearly the usecase where a graph database is useful. Even if I'm not convinced by the "model free" approach.
Is there a good scala-connector or should we use java's directly ?

**Comment by callicles** [comment]
There is an Anorm like adpater for the database so that we can connect with a REST API. As a consequence even though the model is free under the hood, will will be enforced in the app.

http://anormcypher.org/

**Comment by osakatand** [comment]
+1 for graph db because it's fun to use. The anorm cypher looks good enough.

**Comment by callicles** [comment]
I stumbled upon this:
https://www.arangodb.com/2015/06/multi-model-benchmark/

Since we are not tight to anything peculiar yet, we could consider it.

**Comment by callicles** [comment]
There is also OrientDb that could be considered.

**Comment by callicles** [comment]
http://www.stingergraph.com/data/uploads/papers/ppaa2014.pdf

**Comment by callicles** [comment]
I will try to make some benchmark Thursday or Friday

**Comment by callicles** [comment]
Arango is a 

> mostly memory database 

won't handle our potential workload I think
