### ISSUE TITLE
Should we make an initial rating for all existing repos?

### ISSUE THREAD

**Issue by osakatand** [gitlinks/github-rank-project#9]
If only the rated repositories are listed on the website there will be too few to be interesting when people are looking for something.
I suggest we make a initial rating of all github repos based on common criteria (stars, forks...) so at the beginning of the website all the projects are listed and the order is just improved with the users ratings.
Otherwise it won't be a reliable place to find a project.

**Comment by callicles** [comment]
This gets backs to having automatic scores. The purpose of having people rate the repos is not to have automatic ratings that are controverses.

Maybe we could compute some automatic score which have lot less weight than people's rate.

Or have an on boarding strategy :)
